name: pyapi-demo
on:
    push: 
       paths:
         - ".github/workflows/demopy.yml"
         - "demoapp/**"
    workflow_dispatch: #manualrun
jobs:
   build:
      name: build-python-api
      runs-on: [self-hosted, Linux, X64]
      steps:
        - run: pwd && ls -al
        - uses: actions/checkout@v4
        - run: python --version
        - run: pwd && ls -al
          name: display all the foder contents
        - uses: actions/setup-python@v5
          with:
            python-version: '3.9' 
        - run: pip install flask
        - run: python demoapp.py
          working-directory: ./demoapp
          name: run the python-demo app
